import torch
import numpy as np
import cv2
from transformers import Swin2SRForImageSuperResolution, Swin2SRImageProcessor
from typing import List

class GaugeScaleSuperResolution:
    def __init__(self, config: dict):
        self.config = config
        self.model_name = self.config.get('model_name', '')

        requested_device = self.config.get('device', 0)
        if isinstance(requested_device, (int, list)) and not torch.cuda.is_available():
            print("Warning: GPU requested but CUDA is not available. Falling back to CPU for Super Resolution.")
            self.device = 'cpu'
        else:
            self.device = requested_device

        self.processor = None
        self.model = None
        self._load_model()
    
    def _load_model(self):
        print(f"Attempting to load model '{self.model_name}' to {self.device}...")
        try:
            self.processor = Swin2SRImageProcessor()
            self.model = Swin2SRForImageSuperResolution.from_pretrained(self.model_name).to(self.device).half().eval()
       
        except OSError as e:
            print(f"OSError: Failed to load the model from Hugging Face. Please check the model name or your internet connection.\nDetails: {e}")
            raise

        except RuntimeError as e:
            print(f"RuntimeError: A PyTorch or device error occurred.\nDetails: {e}")
            raise

        except Exception as e:
            print(f"An unexpected error occurred while loading the model: {e}")
            raise

    def get_superresolution_batch(self, images: List[np.ndarray]) -> List[np.ndarray]:
        if not images:
            return []

        max_h = max(img.shape[0] for img in images)
        max_w = max(img.shape[1] for img in images)

        padded_images_rgb = []
        original_sizes = []

        for img in images:
            h, w = img.shape[:2]
            original_sizes.append((h, w)) 
            
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            
            pad_h = max_h - h
            pad_w = max_w - w
            
            if pad_h > 0 or pad_w > 0:
                img_rgb = np.pad(img_rgb, ((0, pad_h), (0, pad_w), (0, 0)), mode='constant', constant_values=0)
            
            padded_images_rgb.append(img_rgb)

        inputs = self.processor(padded_images_rgb, return_tensors="pt").to(self.device).to(torch.float16)
        
        with torch.no_grad():
            outputs = self.model(**inputs).reconstruction 

        results = []
        
        for i in range(outputs.shape[0]):
            # 1. Grab the tensor, convert to float32, and move to CPU
            out_tensor = outputs[i].squeeze().float().cpu()
            
            # 2. FIX: Replace any NaNs or Infs generated by FP16 math in padded regions
            out_tensor = torch.nan_to_num(out_tensor, nan=0.0, posinf=1.0, neginf=0.0)
            
            # 3. Clamp and convert to numpy array
            out = out_tensor.clamp(0, 1).numpy()
            
            out = np.transpose(out, (1, 2, 0)) * 255.0 
            out_uint8 = out.astype(np.uint8)
            
            scale_factor = out_uint8.shape[0] / max_h
            orig_h, orig_w = original_sizes[i]
            
            target_h = int(orig_h * scale_factor)
            target_w = int(orig_w * scale_factor)
            
            # Crop the padding back out
            cropped_out = out_uint8[:target_h, :target_w, :]
            
            results.append(cv2.cvtColor(cropped_out, cv2.COLOR_RGB2BGR))
            
        return results

    def get_superresolution(self, image: np.ndarray) -> np.ndarray:
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        inputs = self.processor(image_rgb, return_tensors="pt").to(self.device).to(torch.float16)
        
        with torch.no_grad():
            output = self.model(**inputs).reconstruction

        out_tensor = output.squeeze().float().cpu()
        
        # FIX applied here as well for stability
        out_tensor = torch.nan_to_num(out_tensor, nan=0.0, posinf=1.0, neginf=0.0)
        
        out = out_tensor.clamp(0, 1).numpy()
        out = np.transpose(out, (1, 2, 0)) * 255.0
        out_uint8 = out.astype(np.uint8)
        
        return cv2.cvtColor(out_uint8, cv2.COLOR_RGB2BGR)